apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"igor"'
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: igor
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.30.1
    cluster: spin-igor
  name: spin-igor
  namespace: ssd-spin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-igor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        moniker.spinnaker.io/application: spin
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: igor
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.30.1
        cluster: spin-igor
        ssd.admissionreview.accountname: production
        ssd.admissionreview.appname: ssd-spin
    spec:
      affinity: {}
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=100.0
        - name: SPRING_PROFILES_ACTIVE
          value: overrides,local
        image: quay.io/opsmxpublic/ubi8-igor-cve:1.30.1-24b976b-202403060612-dev
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: igor
        ports:
        - containerPort: 8088
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8088/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 650Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-igor-files-1705123742
        - mountPath: /etc/pki/ca-trust/extracted/java
          name: oes-cacerts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-igor-files-1705123742
        secret:
          defaultMode: 420
          secretName: spin-igor-files-1705123742
      - name: oes-cacerts
        secret:
          defaultMode: 420
          secretName: oes-cacerts
