apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"deck"'
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: deck
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.30.1
    cluster: spin-deck
  name: spin-deck
  namespace: ssd-spin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-deck
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        moniker.spinnaker.io/application: spin
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: deck
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.30.1
        cluster: spin-deck
        ssd.admissionreview.accountname: production
        ssd.admissionreview.appname: ssd-spin
    spec:
      affinity: {}
      containers:
      - env:
        - name: API_HOST
          value: http://spin-gate:8084
        image: quay.io/opsmxpublic/ubi8-oes-custom-deck-cve:3f94c6334
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: deck
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-deck-files-1359372484
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-deck-files-1359372484
        secret:
          defaultMode: 420
          secretName: spin-deck-files-1359372484
